# This is a basic workflow to help you get started with Actions
name: exporting api to github repo

on:
  workflow_dispatch:
    inputs:
      apim_name:
        type: APIM service
        description: mention the apim service name
      api_name:
        type: Deployed API
        description: mention the deployed api name for which the OpenAPI spec to be exported

      api_specification_format:
        type: specification format of API
        description: mention the API specification format
        options:
        - OpenApi
        - Wadl, 
        - Swagger 
        - Wsdl
        - OpenApiJson

jobs:  
  build-and-deploy:
    name: build-release
    runs-on: self-hosted    
    environment: dev
    permissions:
          contents: read
          pages: write
          id-token: write 
    steps:          
      # Checkout code
      - uses: actions/checkout@main

      - name: Log into Azure
        uses: Azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: poweshell
        shell: pwsh
        run: |
          cd /home/etpAdmin/api_export_specs
          rm emcp-echo.yaml
          $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName "etpxapimdata" -ServiceName "etpx-apim-cicd"
          Export-AzApiManagementApi -Context $ApiMgmtContext -ApiId "emcp-echo" -SpecificationFormat "OpenApi" -SaveAs "/home/etpAdmin/api_export_specs/emcp-echo.yaml"

      - name: initialise the git
        run: |
          cd /home/etpAdmin/api_export_specs
          git init
          git add emcp-echo.yaml
          git status
          
      - name: git add the remote origin and fetch
        run: |
          cd /home/etpAdmin/api_export_specs
          git remote -v
          git remote add origin https://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@github.schneider-electric.com/etpx-platform/etpx-apim-open-specs.git
          git remote -v
          git fetch
        continue-on-error: true

      - name: git Checkout branch main
        run: |
          cd /home/etpAdmin/api_export_specs
          git commit -m 'open spec file from APIM'
          git checkout main
          git branch

      - name: push the exported API spec to etpx-apim-open-specs repository
        run: |
          cd /home/etpAdmin/api_export_specs
          git push https://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@github.schneider-electric.com/etpx-platform/etpx-apim-open-specs.git
